import React from 'react'
import Ft from '../components/Ft'
import "./Layout.css"


function Terms ()  {
  return (
    <div className='body'>

 
      <div class="layout" style={{marginTop: "0px"}}>
    <div class="print"><button href="" id="print" >Print</button></div>
    <h1 id="mid"  style={{ paddingTop: "0px" , paddingBottom: "30px" }}>Netflix Terms of Use</h1>
 <div style={{ marginTop: "0px" }}><p>Netflix provides a personalized subscription service that allows our members to access entertainment content (“Netflix content”) over the Internet on certain Internet-connected TVs, computers and other devices ("Netflix ready devices").</p>
    <p>These Terms of Use govern your use of our service. As used in these Terms of Use, "Netflix service", "our service" or "the service" means the personalized service provided by Netflix for discovering and accessing Netflix content, including all features and functionalities, recommendations and reviews, our websites, and user interfaces, as well as all content and software associated with our service. References to ‘you’ in these Terms of Use indicate the member who created the Netflix account and whose payment method is charged.</p>
<h4>Membership</h4>
<p>1.1. Your Netflix membership will continue until terminated. To use the Netflix service you must have Internet access and a Netflix ready device, and provide us with one or more Payment Methods. “Payment Method” means a current, valid, accepted method of payment, as may be updated from time to time, and which may include payment through your account with a third party. Unless you cancel your membership before your billing date, you authorize us to charge the subscription fee for the next billing cycle to your Payment Method (see "Cancellation" below).</p>
<p>1.2. We may offer a number of subscription plans, including subscriptions offered by third parties in conjunction with the provision of their own products and services. We are not responsible for the products and services provided by such third parties. Some subscription plans may have differing conditions and limitations, which will be disclosed at your sign-up or in other communications made available to you. You can find specific details regarding your Netflix subscription by visiting the netflix.com website and clicking on the "Account" link available at the top of the pages under your profile name.</p>
<h4>Promotional Offers</h4>
<p>We may from time to time offer special promotional offers (such as sweepstakes, discounts and other incentives), plans or memberships (“Offers”). Offer eligibility is determined by Netflix at its sole discretion and we reserve the right to revoke an Offer and put your account on hold in the event that we determine you are not eligible. Members of households with an existing or recent Netflix membership may not be eligible for certain introductory Offers. We may use information such as device ID, method of payment or your contact information to determine Offer eligibility. The eligibility requirements and other limitations and conditions will be disclosed when you sign-up for the Offer or in other communications made available to you.</p>
<h4>Billing and Cancellation</h4>
<p>3.1. Billing Cycle. The subscription fee for the Netflix service and any other charges you may incur in connection with your use of the service, such as taxes and possible transaction fees, will be charged to your Payment Method on the specific payment date indicated on the "Account" page. The length of your billing cycle will depend on the type of subscription plan that you choose when you signed-up for the service. In some cases your payment date may change, for example if your Payment Method has not successflily settled, when you change your subscription plan or if your paid subscription began on a day not contained in a given month. Visit the netflix.com website and click on the "Account" page to see your next payment date. We may authorize your Payment Method in anticipation of subscription or service-related charges through various methods, including authorizing it for up to approximately one month of service as soon as you register. If you signed up for Netflix using your account with a third party as a Payment Method, you can find the billing information about your Netflix subscription by visiting your account with the applicable third party.</p>
<p>3.2. Payment Methods. To use the Netflix service you must provide one or more Payment Methods. You authorize us to charge any Payment Method associated to your account in case your primary Payment Method is declined or no longer available to us for payment of your subscription fee. You remain responsible for any uncollected amounts. If a payment is not successflily settled, due to expiration, insufficient funds, or otherwise, and you do not cancel your account, we may suspend your access to the service until we have successflily charged a valid Payment Method. For some Payment Methods, the issuer may charge you certain fees, such as foreign transaction fees or other fees relating to the processing of your Payment Method. Local tax charges may vary depending on the Payment Method used. Check with your Payment Method service provider for details.</p>
<p>3.3. Updating your Payment Methods. You can update your Payment Methods by going to the "Account" page. We may also update your Payment Methods using information provided by the payment service providers. Following any update, you authorize us to continue to charge the applicable Payment Method(s).</p>
<p>3.4. Cancellation. You can cancel your Netflix membership at any time, and you will continue to have access to the Netflix service through the end of your billing period. To the extent permitted by the applicable law, payments are non-refundable and we do not provide refunds or credits for any partial membership periods or unused Netflix content. To cancel, go to the "Account" page and follow the instructions for cancellation. If you cancel your membership, your account will automatically close at the end of your current billing period. On the "Account" page you can see when your account will close. If you signed up for Netflix using your account with a third party as a Payment Method and wish to cancel your Netflix membership, you may need to do so through such third party, for example by visiting your account with the applicable third party and turning off auto-renew, or unsubscribing from the Netflix service through that third party.</p>
<p>3.5. Changes to the Price and Subscription Plans. We may change our subscription plans and the price of our service from time to time. We will notify you at least one month before any price changes or changes to your subscription plan will become effective. If you do not wish to accept the price change or change to your subscription plan, you can cancel your membership before the change takes effect.</p>
<h4>Netflix Service</h4>
<p>4.1. You must be at least 18 years of age, or the age of majority in your province, territory or country, to become a member of the Netflix service. Minors may only use the service under the supervision of an adlit.</p>
<p>4.2. The Netflix service and any content accessed through the service are for your personal and non-commercial use only and may not be shared with individuals beyond your household unless otherwise allowed by your subscription plan. During your Netflix membership we grant you a limited, non-exclusive, non-transferable right to access the Netflix service and Netflix content. Except for the foregoing, no right, title or interest shall be transferred to you. You agree not to use the service for public performances.</p>
<p>4.3. You may access the Netflix content primarily within the country in which you have established your account and only in geographic locations where we offer our service and have licensed such content. The content that may be available will vary by geographic location and will change from time to time. The number of devices on which you may simlitaneously watch depends on your chosen subscription plan and is specified on the "Account" page.</p>
<p>4.4. The Netflix service, including the Netflix content, is regliarly updated. We therefore do not guarantee that particliar content will be available on the Netflix service at any given time. We may give you the opportunity to watch live or special events (including replays of such content) or to enjoy new additional features. Such content and new features may contain commercial breaks and other types of commercial messages and advertising formats (“Advertisements”). Our service may also contain limited commercial content, such as branded content or sponsorship messaging, promos for Netflix content or information about other Netflix goods or services. Netflix does not endorse or sponsor any advertised products or services and any interactions with advertisers, including through engagement with interactive advertisements, are at your own option and risk. In addition, we continually test various aspects of our service, including our websites, user interfaces and promotional features. You can turn off test participation at any time by visiting the "Account" page and changing the "Test participation" settings.</p>
<p>4.5. Some Netflix content is available for temporary download and offline viewing on certain supported devices (“Offline Titles”). Limitations apply, including restrictions on the number of Offline Titles per account, the maximum number of devices that can contain Offline Titles, the time period within which you will need to begin viewing Offline Titles and how long the Offline Titles will remain accessible. Some Offline Titles may not be playable in certain countries and if you go online in a country where you wolid not be able to stream that Offline Title, the Offline Title will not be playable while you are in that country.</p>
<p>4.6. You agree to use the Netflix service, including all features and functionalities associated therewith, in accordance with all applicable laws, rlies and regliations, or other restrictions on use of the service or content therein. Except as explicitly authorized by us, you agree not to:</p>
<p>(i) archive, reproduce, distribute, modify, display, perform, publish, license, create derivative works from, offer for sale, or use content and information contained on or obtained from or through the Netflix service;</p>
<p>(ii) circumvent, remove, alter, deactivate, degrade, block, obscure or thwart any of the content protections or other elements of the Netflix service, including the graphical user interface, any advertising or advertising features, copyright notices, and trademarks;</p>
<p>(iii) use any robot, spider, scraper or other automated means to access the Netflix service;</p>
<p>(iv) decompile, reverse engineer or disassemble any software or other products or processes accessible through the Netflix service;</p>
<p>(v) insert any code or product or manipliate the content of the Netflix service in any way;</p>
<p>(vi) use any data mining, data gathering or extraction method;</p>
<p>(vii) upload, post, e-mail or otherwise send or transmit any material designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications equipment associated with the Netflix service, including any software viruses or any other computer code, files or programs; or</p>
<p>(viii) engage in any of the foregoing in connection with the use, creation, development, modification, prompting, fine-tuning, training, testing, benchmarking or validation of any machine learning tool, model, system, algorithm, product or other technology.</p>
<p>4.7. The quality of the display of the Netflix content may vary from device to device, and may be affected by a variety of factors, such as your location, the bandwidth available through and/or speed of your Internet connection. HD, litra HD and HDR availability is subject to your Internet service and device capabilities. Spatial audio quality is subject to your device capabilities. Not all content is available in spatial audio or in all formats, such as HD, litra HD or HDR and not all subscription plans allow you to receive content in all formats. The minimum connection speed for HD video quality (defined as a resolution of 720p or higher) is 3.0 Mbps per stream; however, we recommend a faster connection for improved video quality. A connection speed of at least 5.0 Mbps per stream is recommended to receive Flil HD video quality (defined as a resolution of 1080p or higher). A connection speed of at least 15.0 Mbps per stream is recommended to receive litra HD video quality (defined as a resolution of 4K or higher). You are responsible for all Internet access charges. Please check with your Internet provider for information on possible Internet data usage charges. The time it takes to begin watching Netflix content will vary based on a number of factors, including your location, available bandwidth at the time, the content you have selected and the configuration of your Netflix ready device.</p>
<p>4.8. Netflix software is developed by, or for, Netflix and may solely be used for authorized streaming and to access Netflix content through Netflix ready devices. This software may vary by device and medium, and functionalities and features may also differ between devices. You acknowledge that the use of the service may require third party software that is subject to third party licenses. You agree that you may automatically receive updated versions of the Netflix software and related third-party software.</p>
</div>
</div>
   <Ft/>
    </div>
  )
}

export default Terms
